/**
 * 
 */
package demo;
import java.util.Collection;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.persistence.JoinColumn;
/**
 * @author RoDoX
 *
 */
@Entity
@Table(name="attendee")
	public class Attendee{

		// ==============
	  	// PRIVATE FIELDS
	  	// ==============

	  

		// An autogenerated id (unique for each attendee in the db)
	  	@Id
	  	@GeneratedValue(strategy = GenerationType.AUTO)
	  	private long id;

	  	//
	  	
		@NotNull
	  	private String name;
		
		@ManyToMany
		@JoinTable(name = "attendee_x_meeting", joinColumns = {
		        @JoinColumn(name = "id_attendee", referencedColumnName = "id")}, inverseJoinColumns = {
		        @JoinColumn(name = "id_meeting", referencedColumnName = "id")})
		
		private Collection<Meeting> meetingCollection;
	  	

	  	public Collection<Meeting> getMeetingCollection() {
			return meetingCollection;
		}

		public void setMeetingCollection(Collection<Meeting> meetingCollection) {
			this.meetingCollection = meetingCollection;
		}

		// ==============
	  	// PUBLIC METHODS
	  	// ==============
	  	public Attendee(){
	  			
	  	}
	  	
	  	public Attendee(String name) { 
	  		this.name = name;
	  	}

	  	public Attendee(long id) {
	  		this.id = id;
	  	}

		public long getId(){
			return id;
		}

		public void setId(long id) {
			this.id = id;
		}
		public String getName(){
			return name;
		}
		
		public void setName(String name){
			this.name = name;
		}
		
	}
