/**
 * 
 */
package demo;


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * @author RoDoX
 *
 */
@Entity
@Table(name="room")
	public class Room {

		// ==============
	  	// PRIVATE FIELDS
	  	// ==============

	  	// An autogenerated id (unique for each user in the db)
	  	@Id
	  	@GeneratedValue(strategy = GenerationType.AUTO)
	  	private long id;

	  	//
	  	
		@NotNull
	  	private String name;
		
	  	@NotNull
	  	private String description;
	  	
	  	@NotNull
	  	private int capacity;
	  	
	  	 /*@OneToMany(fetch = FetchType.LAZY, mappedBy = "room")
	     private Set<Meeting> meetingCollection;
*/
	  	

	  

		// ==============
	  	// PUBLIC METHODS
	  	// ==============
	  	public Room(){
	  			
	  	}
	  	
	  	public Room(String name, String description, int capacity) { 
	  		this.name = name;
	  		this.description = description;
	  		this.capacity = capacity;
	  	}

	  	
	  	
	  	

		public int getCapacity() {
			return capacity;
		}

		public void setCapacity(int capacity) {
			this.capacity = capacity;
		}

		public Room(long id) {
	  		this.id = id;
	  	}

		public long getId(){
			return id;
		}

		public void setId(long id) {
			this.id = id;
		}
		public String getName(){
			return name;
		}
		
		public void setName(String name){
			this.name = name;
		}
		
		public String getDescription() {
			return description;
		}

		public void setDescription(String description) {
			this.description = description;
		}
	  	

	 

}
