-- MySQL Script generated by MySQL Workbench
-- 02/05/15 23:16:51
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema meeting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `meeting` ;
CREATE SCHEMA IF NOT EXISTS `meeting` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `meeting` ;

-- -----------------------------------------------------
-- Table `meeting`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting`.`room` ;

CREATE TABLE IF NOT EXISTS `meeting`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meeting`.`attendee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting`.`attendee` ;

CREATE TABLE IF NOT EXISTS `meeting`.`attendee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meeting`.`time_slot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting`.`time_slot` ;

CREATE TABLE IF NOT EXISTS `meeting`.`time_slot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start` TIME NULL,
  `end` TIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meeting`.`meeting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting`.`meeting` ;

CREATE TABLE IF NOT EXISTS `meeting`.`meeting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_room` INT NOT NULL,
  `id_time_slot` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `id_room_idx` (`id_room` ASC),
  INDEX `id_time_slot_idx` (`id_time_slot` ASC),
  CONSTRAINT `id_room`
    FOREIGN KEY (`id_room`)
    REFERENCES `meeting`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_time_slot`
    FOREIGN KEY (`id_time_slot`)
    REFERENCES `meeting`.`time_slot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `meeting`.`attendee_x_meeting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `meeting`.`attendee_x_meeting` ;

CREATE TABLE IF NOT EXISTS `meeting`.`attendee_x_meeting` (
  `id_attendee` INT NOT NULL,
  `id_meeting` INT NOT NULL,
  PRIMARY KEY (`id_attendee`, `id_meeting`),
  INDEX `id_meeting_idx` (`id_meeting` ASC),
  CONSTRAINT `id_attendee`
    FOREIGN KEY (`id_attendee`)
    REFERENCES `meeting`.`attendee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_meeting`
    FOREIGN KEY (`id_meeting`)
    REFERENCES `meeting`.`meeting` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
